# Generated by Django 5.0.7 on 2024-07-24 06:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='voter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('JOE', 'Joe Biden'), ('HARRIS', 'Kamala Harris'), ('OBAMA', 'Barack Obama'), ('TRUMP', 'Donald Trump'), ('MIKE', 'Mike Pence'), ('HALLEY', 'Nikki Halley'), ('KENNEDY', 'Robert F. Kennedy Jr'), ('WEST', 'Cornel West'), ('OLIVER', 'Chase Oliver'), ('NO VOTE', 'No')], default='NO VOTE', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
